# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SSayyed\Documents\Git-Repo\BackOffice\ui\Employees.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore,QtGui,QtWidgets
import db2
from PyQt5.QtCore import *
import datetime
from showEmployee import empdata
from editemployees import Edit_emp_data
from PyQt5.QtWidgets import QMessageBox
from datetime import datetime as dt



class Ui_EmployeeWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(708, 642)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 60, 16))
        self.label_3.setObjectName("label_3")
        self.marital_comboBox = QtWidgets.QComboBox(self.page)
        self.marital_comboBox.setGeometry(QtCore.QRect(400, 150, 104, 26))
        self.marital_comboBox.setObjectName("marital_comboBox")
        self.marital_comboBox.addItem("")
        self.marital_comboBox.addItem("")
        self.marital_comboBox.addItem("")
        self.emp_no_field = QtWidgets.QLineEdit(self.page)
        self.emp_no_field.setGeometry(QtCore.QRect(70, 30, 201, 21))
        self.emp_no_field.setObjectName("emp_no_field")
        self.lname_field = QtWidgets.QLineEdit(self.page)
        self.lname_field.setGeometry(QtCore.QRect(70, 110, 201, 21))
        self.lname_field.setObjectName("lname_field")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 60, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 60, 16))
        self.label_5.setObjectName("label_5")
        self.ss_field = QtWidgets.QLineEdit(self.page)
        self.ss_field.setGeometry(QtCore.QRect(70, 70, 201, 21))
        self.ss_field.setObjectName("ss_field")
        self.fname_field = QtWidgets.QLineEdit(self.page)
        self.fname_field.setGeometry(QtCore.QRect(70, 150, 201, 21))
        self.fname_field.setObjectName("fname_field")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(320, 30, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(320, 70, 111, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(320, 110, 60, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(510, 110, 31, 21))
        self.label_9.setObjectName("label_9")
        self.address1_field = QtWidgets.QLineEdit(self.page)
        self.address1_field.setGeometry(QtCore.QRect(420, 30, 251, 21))
        self.address1_field.setObjectName("address1_field")
        self.address2_field = QtWidgets.QLineEdit(self.page)
        self.address2_field.setGeometry(QtCore.QRect(420, 70, 251, 21))
        self.address2_field.setObjectName("address2_field")
        self.phone_field = QtWidgets.QLineEdit(self.page)
        self.phone_field.setGeometry(QtCore.QRect(380, 110, 111, 21))
        self.phone_field.setObjectName("phone_field")
        self.alt_field = QtWidgets.QLineEdit(self.page)
        self.alt_field.setGeometry(QtCore.QRect(540, 110, 131, 21))
        self.alt_field.setObjectName("alt_field")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(310, 150, 91, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(520, 150, 31, 21))
        self.label_11.setObjectName("label_11")
        self.sex_comboBox = QtWidgets.QComboBox(self.page)
        self.sex_comboBox.setGeometry(QtCore.QRect(550, 150, 104, 26))
        self.sex_comboBox.setObjectName("sex_comboBox")
        self.sex_comboBox.addItem("")
        self.sex_comboBox.addItem("")
        self.sex_comboBox.addItem("")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(10, 200, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(10, 250, 71, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page)
        self.label_14.setGeometry(QtCore.QRect(300, 210, 131, 16))
        self.label_14.setObjectName("label_14")
        
        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(10, 300, 71, 21))
        self.label_15.setObjectName("label_15")
        
        
        self.date_hired = QtWidgets.QDateEdit(self.page)
        self.date_hired.setGeometry(QtCore.QRect(80, 200, 110, 24))
        self.date_hired.setObjectName("date_hired")
        self.date_left = QtWidgets.QDateEdit(self.page)
        self.date_left.setGeometry(QtCore.QRect(80, 250, 110, 24))
        self.date_left.setObjectName("date_left")
        
        self.position = QtWidgets.QComboBox(self.page)
        self.position.setGeometry(QtCore.QRect(80, 300, 110, 24))
        self.position.setObjectName("position_combox")
        c=db2.conn.cursor()
        c.execute("SELECT positionid FROM position")
        res = c.fetchall()
        for i in res:
            self.position.addItem(str(i[0]))
                
        self.termination_comboBox = QtWidgets.QComboBox(self.page)
        self.termination_comboBox.setGeometry(QtCore.QRect(400, 210, 241, 26))
        self.termination_comboBox.setObjectName("termination_comboBox")
        self.termination_comboBox.addItem("")
        self.termination_comboBox.setItemText(0, "")
        self.termination_comboBox.addItem("")
        self.termination_comboBox.addItem("")
        self.termination_comboBox.addItem("")
        self.termination_comboBox.addItem("")
        self.termination_comboBox.addItem("")
        self.termination_comboBox.addItem("")
        
        self.add_button = QtWidgets.QPushButton(self.page)
        self.add_button.setGeometry(QtCore.QRect(280, 260, 401, 32))
        self.add_button.setObjectName("add_button")
        self.add_button.clicked.connect(self.add_employee)
        self.add_button.clicked.connect(self.clear)


        self.info_button = QtWidgets.QPushButton(self.page)
        self.info_button.setGeometry(QtCore.QRect(330, 310, 311, 32))        
        self.info_button.setObjectName("info_button")        
        self.info_button.clicked.connect(self.details)
        
        self.info_button2 = QtWidgets.QPushButton(self.page)
        self.info_button2.setGeometry(QtCore.QRect(380, 360, 221, 32))        
        self.info_button2.setObjectName("info_button")        
        self.info_button2.clicked.connect(self.editDetail)
        
        
        StackedWidget.addWidget(self.page)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")

        StackedWidget.addWidget(self.page1)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.label_2.setText(_translate("StackedWidget", "Emp   #"))
        self.label_3.setText(_translate("StackedWidget", "L. Name"))
        self.marital_comboBox.setItemText(0, _translate("StackedWidget", "Unknown"))
        self.marital_comboBox.setItemText(1, _translate("StackedWidget", "Single"))
        self.marital_comboBox.setItemText(2, _translate("StackedWidget", "Married"))
        self.label_4.setText(_translate("StackedWidget", "SS #"))
        self.label_5.setText(_translate("StackedWidget", "F. Name"))
        self.label_6.setText(_translate("StackedWidget", "Address <Line 1>"))
        self.label_7.setText(_translate("StackedWidget", "Address < Line 2>"))
        self.label_8.setText(_translate("StackedWidget", "Phone #"))
        self.label_9.setText(_translate("StackedWidget", "Alt #"))
        self.label_10.setText(_translate("StackedWidget", "Marital Status"))
        self.label_11.setText(_translate("StackedWidget", "Sex"))
        self.sex_comboBox.setItemText(0, _translate("StackedWidget", "Male"))
        self.sex_comboBox.setItemText(1, _translate("StackedWidget", "Female"))
        self.sex_comboBox.setItemText(2, _translate("StackedWidget", "Unknow"))
        self.label_12.setText(_translate("StackedWidget", "Date Hired"))
        self.label_13.setText(_translate("StackedWidget", "Date Left"))
        self.label_14.setText(_translate("StackedWidget", "Termination Reason"))
        self.label_15.setText(_translate("StackedWidget", "Position ID"))
        self.termination_comboBox.setItemText(1, _translate("StackedWidget", "Incompetence"))
        self.termination_comboBox.setItemText(2, _translate("StackedWidget", "Insubordination"))
        self.termination_comboBox.setItemText(3, _translate("StackedWidget", "Attendance Issues"))
        self.termination_comboBox.setItemText(4, _translate("StackedWidget", "Criminal Behavior"))
        self.termination_comboBox.setItemText(5, _translate("StackedWidget", "Temporary Hire"))
        self.termination_comboBox.setItemText(6, _translate("StackedWidget", "Accepted New Position"))
        self.add_button.setText(_translate("StackedWidget", "Add Employee"))
        self.info_button.setText(_translate("StackedWidget", "Show Employees"))
        self.info_button2.setText(_translate("StackedWidget","Edit Employees"))



    def add_employee(self):
        mycursor = db2.conn.cursor()
        insert_sql = "INSERT INTO employees(employeeid, socialsecuritynumber, firstname,lastname, addressline1, addressline2, mobilephone, alternatephone, maritialstatus, gender, hireddate, resignationdate, terminationreason,positionid) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
        data = tuple((self.emp_no_field.text(),self.ss_field.text(),self.fname_field.text(),self.lname_field.text(),self.address1_field.text(),self.address2_field.text(),self.phone_field.text(),self.alt_field.text(),self.marital_comboBox.currentText(),self.sex_comboBox.currentText(),self.date_hired.dateTime().toString("MM dd yyyy"),self.date_left.dateTime().toString("MM dd yyyy"),self.termination_comboBox.currentText(),self.position.currentText()))
        mycursor.execute(insert_sql,data)
        db2.conn.commit()
        print(data)
       
        if mycursor.rowcount == 1:
            msg = QMessageBox()
            msg.setWindowTitle("Success")
            msg.setText("Employee Added Successfully !")
            x = msg.exec_()
        print(mycursor.rowcount,"inserted successfully")
     
    def clear(self):
        self.emp_no_field.clear()
        self.ss_field.clear()
        self.fname_field.clear()
        self.lname_field.clear()
        self.address1_field.clear()
        self.address2_field.clear()
        self.phone_field.clear()
        self.alt_field.clear()
        self.marital_comboBox.clear()
               
    def details(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = empdata()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        #self.exec()
    def editDetail(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Edit_emp_data()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
'''
class MainWindow(QtWidgets.QMainWindow, mainwindow.Ui_MainWindow):
    def __init__(self):
        super(self.__class__, self).__init__()
        self.setupUi(self)
'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StackedWidget = QtWidgets.QStackedWidget()
    ui = Ui_EmployeeWidget()
    ui.setupUi(StackedWidget)
    StackedWidget.show()
    sys.exit(app.exec_())
