# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateInventory.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtSql import QSqlDatabase, QSqlQuery, QSqlTableModel
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableView,QVBoxLayout,QPushButton,QHBoxLayout,QApplication,QWidget
import db2

class Ui_InventoryUpdate(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(570, 580)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(20, 10, 671, 491))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 510, 511, 41))
        self.pushButton.setObjectName("pushButton")
        self.tableView_2 = QtWidgets.QTableView(Dialog)
        self.tableView_2.setGeometry(QtCore.QRect(440, 10, 671, 491))
        self.tableView_2.setObjectName("tableView_2")
        self.tableView.setEditTriggers(QtWidgets.QTableView.NoEditTriggers)

        self.db = QSqlDatabase.addDatabase("QSQLITE")
        self.db.setDatabaseName("ems.db")
        self.db.open()
        self.model = QSqlTableModel()
        
        self.pushButton.clicked.connect(self.insdata)
        self.initializedModel()
        
        self.tableView.setModel(self.model)
        self.tableView.hideColumn(0)
        self.tableView.hideColumn(5)
        self.tableView.hideColumn(6)
        self.tableView.hideColumn(7)
        self.tableView.hideColumn(8)
        self.tableView.hideColumn(9)
        self.tableView.hideColumn(10)
        
        self.tableView_2.setModel(self.model)
        self.tableView_2.hideColumn(0)
        self.tableView_2.hideColumn(1)
        self.tableView_2.hideColumn(2)
        self.tableView_2.hideColumn(3)
        self.tableView_2.hideColumn(4)
        self.tableView_2.hideColumn(5)
        self.tableView_2.hideColumn(7)
        self.tableView_2.hideColumn(8)
        self.tableView_2.hideColumn(9)
        self.tableView_2.hideColumn(10)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        
    def initializedModel(self):
        self.model.setTable("inventory")
        self.model.setEditStrategy(QSqlTableModel.OnFieldChange)
        self.model.select()
        
    def insdata(self):
        cur=db2.conn.cursor()
        sql2 = ("SELECT inventoryId,unitofmeasure FROM inventory")
        cur.execute(sql2)
        res = cur.fetchall()
        for i in res:     
            cur2 = db2.conn.cursor()
            try:
                sql = ("INSERT INTO inventoryPurchase (inventoryid,unitofmeasure) values (?,?)" )
                cur2.execute(sql,(i))
                db2.conn.commit()    
            except Exception as e:
                print(e)    

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Add Inventory"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_InventoryUpdate()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
