# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\SSayyed\Documents\Git-Repo\BackOffice\ui\showEmployee.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
import db2


class Inventory_Data(object):
    
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 536, 551))
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(70, 1, 151, 23))
        self.label.setFont(QFont('Times', 10))
        self.label.setObjectName("label")
        # self.pushButton.clicked.connect(self.load_data)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        mycursor=db2.conn.cursor()
        query = "SELECT sku,name,unitofmeasure,currentstock,reorderquantity FROM inventory"
        mycursor.execute(query)
        mycursor.fetchone()
        a= [desc[0] for desc in mycursor.description]
        self.tableWidget.setHorizontalHeaderLabels(a)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        mycursor = db2.conn.cursor()
        query = "SELECT sku,name,unitofmeasure,currentstock,reorderquantity FROM inventory"
        data = mycursor.execute(query)
        result = mycursor.fetchall()
        self.tableWidget.setRowCount(0)
        for row_number,row_data in enumerate(result):
            self.tableWidget.insertRow(row_number)
            for column_number,data in enumerate(row_data):
                self.tableWidget.setItem(row_number,column_number,QtWidgets.QTableWidgetItem(str(data)))

        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow","Inventory View"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Inventory_Data()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
