# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InventoryMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from InventoryUpdate import Ui_InventoryUpdate
from InventoryView import Inventory_Data
from InventoryCreate import Ui_InventoryCreate
class Ui_InventoryMenu(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Inventory Menu")
        Dialog.resize(336, 444)
        self.create_button = QtWidgets.QPushButton(Dialog)
        self.create_button.setGeometry(QtCore.QRect(90, 280, 151, 71))
        self.create_button.setObjectName("pushButton")
        self.update_button = QtWidgets.QPushButton(Dialog)
        self.update_button.setGeometry(QtCore.QRect(90, 100, 151, 71))
        self.update_button.setObjectName("pushButton_2")
        self.view_button = QtWidgets.QPushButton(Dialog)
        self.view_button.setGeometry(QtCore.QRect(90, 190, 151, 71))
        self.view_button.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.update_button.clicked.connect(lambda: self.openupdate())
        self.view_button.clicked.connect(lambda:self.openView())
        self.create_button.clicked.connect(lambda:self.openCreatewindow())

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Inventory Menu"))
        self.create_button.setText(_translate("Dialog", "Create Inventory"))
        self.update_button.setText(_translate("Dialog", "Update Inventory"))
        self.view_button.setText(_translate("Dialog", "View Inventory"))


    def openupdate(self):
        self.window=QtWidgets.QDialog()
        self.ui=Ui_InventoryUpdate()
        self.ui.setupUi(self.window)    
        self.window.show()
        
    def openView(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Inventory_Data()
        self.ui.setupUi(self.window)    
        self.window.show()
    
    def openCreatewindow(self):
        self.window=QtWidgets.QDialog()
        self.ui=Ui_InventoryCreate()
        self.ui.setupUi(self.window)    
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_InventoryMenu()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
