# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
import mainwindow
from EmployeeView import Ui_other_login
import db2



class Ui_login(object):
    def setupUi(self, Dialog):
        
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 640)
        self.login_button = QtWidgets.QPushButton(Dialog)
        self.login_button.setGeometry(QtCore.QRect(180, 350, 113, 32))
        self.login_button.setObjectName("login_button")
        self.username_textfield = QtWidgets.QLineEdit(Dialog)
        self.username_textfield.setGeometry(QtCore.QRect(180, 230, 113, 21))
        self.username_textfield.setObjectName("username_textfield")
        self.password_textfield = QtWidgets.QLineEdit(Dialog)
        self.password_textfield.setGeometry(QtCore.QRect(180, 280, 113, 21))
        self.password_textfield.setObjectName("password_textfield")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 230, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 280, 61, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.login_button.setText(_translate("Dialog", "Login"))
        self.label.setText(_translate("Dialog", "Username"))
        self.label_2.setText(_translate("Dialog", "Password"))

        self.login_button.setCheckable(True)
        self.login_button.clicked.connect(lambda:self.loginCheck())


    def loginCheck(self):
        username = self.username_textfield.text()
        password = self.password_textfield.text()
        mycursor = db2.conn.cursor()
        # sql = ("SELECT firstname,socialsecuritynumber from employees where firstname = ? and socialsecuritynumber = ?")
        
        sql1 = ("SELECT employeeid,firstname,socialsecuritynumber,position.positionname from employees  inner join position on employees.positionid = position.positionid AND (employees.firstname = ? AND employees.socialsecuritynumber = ? )")
        mycursor.execute(sql1,(username,password))
        
        result = mycursor.fetchone()
        if result == None:
            msg = QMessageBox()
            msg.setWindowTitle("Warning")
            msg.setText("Invalid Username And Password!")
            msg.exec_()
            
        elif result[3] == 'manager':  
            db2.emp_list.append(result[0])
            self.loginSystem()      
        else:
            db2.emp_list.append(result[0])
            self.otheremployee()
        return result
        
    def otheremployee(self):
        self.MainWindow = QtWidgets.QDialog()
        self.ui = Ui_other_login()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        
    def loginSystem(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = MainWindow()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        #self.exec()


class MainWindow(QtWidgets.QMainWindow, mainwindow.Ui_MainWindow):
    def __init__(self):
        super(self.__class__, self).__init__()
        self.setupUi(self)
                  

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_login()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
