# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schedule.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import db2
from datetime import datetime as dt

class Ui_ScheduleWidget(object):
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(740, 270)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(120, 30, 201, 22))
        self.comboBox.setObjectName("comboBox")
        
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(490, 30, 201, 22))
        self.comboBox_2.setObjectName("comboBox")
        
        
        cur = db2.conn.cursor()
        cur.execute("SELECT positionname from position") 
        res = cur.fetchall()
        for i in res:
            self.comboBox.addItem(str(i[0]))
        self.comboBox.currentTextChanged.connect(self.dataclear)
        self.comboBox.currentTextChanged.connect(self.datachanged)
        
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 141, 20))
        self.label.setStyleSheet("font: 65 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(350, 30, 141, 20))
        self.label_5.setStyleSheet("font: 65 12pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label")
        
        
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 151, 20))
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(170, 90, 141, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit.setDisplayFormat("dd/MM/yyyy hh:mm:ss")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(480, 90, 141, 22))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.dateTimeEdit_2.setDisplayFormat("dd/MM/yyyy hh:mm:ss")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(330, 90, 151, 20))
        self.label_4.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        # self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 151, 20))
        self.label_6.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_5")
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit_3.setGeometry(QtCore.QRect(170, 140, 141, 22))
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.dateTimeEdit_3.setDisplayFormat("dd/MM/yyyy hh:mm:ss")
        self.dateTimeEdit_4 = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit_4.setGeometry(QtCore.QRect(480, 140, 141, 22))
        self.dateTimeEdit_4.setObjectName("dateTimeEdit_4")
        self.dateTimeEdit_4.setDisplayFormat("dd/MM/yyyy hh:mm:ss")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(320, 140, 151, 20))
        self.label_7.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(150, 200, 351, 31))
        self.pushButton.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.add_schedule)
        self.pushButton.clicked.connect(self.msg)
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Position Name"))
        self.label_3.setText(_translate("Dialog", "Scheduled Start date"))
        self.label_4.setText(_translate("Dialog", "Scheduled End date"))
        self.label_5.setText(_translate("Dialog", "Employee Name"))
        self.label_6.setText(_translate("Dialog", "Shift Start Time"))
        self.label_7.setText(_translate("Dialog", "Shift End Time"))
        self.pushButton.setText(_translate("Dialog", "Add Schedule"))
    
    def dataclear(self):
        self.comboBox_2.clear()
    def datachanged(self):
        name = self.comboBox.currentText()
        sql2 = ("SELECT firstname,employeeid from employees  inner join position on employees.positionid = position.positionid AND position.positionname = ? ")
        cur = db2.conn.cursor()
        cur.execute(sql2,[name])
        ress = cur.fetchall()
        for i in ress:
            self.comboBox_2.addItem(str(i[0]))
                    

    
    def add_schedule(self):
        cur=db2.conn.cursor()
        sql = ("SELECT firstname,employeeid,position.positionname from employees  inner join position on employees.positionid = position.positionid AND employees.firstname = ? ")
        cur.execute(sql,[self.comboBox_2.currentText()])
        res = cur.fetchall()
        for i in res:
            # print(i)
            sql1 = "INSERT INTO schedule (employeeid,scheduleStartDate,scheduleEndDate,createdby) VALUES (?,?,?,?)"
            data = tuple((str(i[1]),self.dateTimeEdit.dateTime().toString("MM dd yyyy hh:mm:ss"),self.dateTimeEdit_2.dateTime().toString("MM dd yyyy hh:mm:ss"),db2.emp_list[0]))
            print(data)
            cur.execute(sql1,data)
            db2.conn.commit()
            
    def msg(self):
        msg = QMessageBox()
        msg.setWindowTitle("Info")
        msg.setText("Schedule Added Successfully!")
        msg.exec_() 
                   
    
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_ScheduleWidget()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
